upstreams:
  image: redis
linked:
  build: linked/
  environment:
    - DOCKER_URL=tcp://172.17.42.1:2375
  links:
    - upstreams:redis
dproxy:
  build: dproxy/
  ports:
    - 8080:80
  links:
    - upstreams:redis


